### ISSUE TITLE
send larger queries to translate faster

### ISSUE THREAD

**Issue by milahu** [Jumpst3r/doctranslate#1]
i made a converter to encode/decode between documents and google translate
see https://github.com/ssut/py-googletrans/issues/99#issuecomment-848714972

currently, `doctranslate` will send each document-paragraph in a separate query

```py
# main.py

    for i in range(len(doc.paragraphs)):
        p = doc.paragraphs[i].text
        printable = set(string.printable)
        p = ''.join(filter(lambda x: x in printable, p))
        print(p)
        res = translator.translate(p, dest=args.output_language).text
        sleep(0.5)
        doc.paragraphs[i].text = res
```

my solution has two benefits:
1\. translate faster
2\. use the google translator webinterface to fix the translation, with the help of google's dictionary

edit: actually this should be implemented in `py-googletrans`

**Comment by Jumpst3r** [comment]
This project was more for research / personal small scale use. For production environments and larger scale translation you should be using google cloud's translate API.  Any other translation library based on the web version of google translate (such as py-googletrans) is inherently unstable and should not be used for production. Large scale automated usage of google webtranslate is probably also against the ToS.
